manifest = "2780f4376249f3b7404c0c5c2ddab84283b3c9945a8da4f45bae1969bee5ffe1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.18.0" ]
revision = "b5192df4146ea29a159a89541d53d2e62117e737"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.18.0" ]
revision = "2e91b07559502eddea823615160c43fe25e3f4c5"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.18.0" ]
revision = "82711bf71bf741a355c4de4dd48b8b7f5d8c83a2"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.18.0" ]
revision = "cf87b20aa4668945b0dac6744c7a6ed7d3e5ce86"
