manifest = "ea5c42d56cad4390c3230ba3076f4a1a4092a82ca54606ab83609ee4ae3941ef"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
target = "//:assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.58.0" ]
revision = "ac721f66265e383ac6d7b96996e902332d12783d"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.58.0" ]
revision = "ba2389bfd836700138f7fbd65858501d75276a05"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.58.0" ]
revision = "56d073a8276bae5f86b88b8e967da2e125280c0b"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.58.0" ]
revision = "a36f15fe51460b013e423ed1c83a0fcb719752ba"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.58.0" ]
revision = "2b5f853e75e5811875cc344e5a6824cec279e9a7"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.58.0" ]
revision = "f777b1eef66c8145f13ab1077dc6585fbbb7f26a"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.58.0" ]
revision = "95bd2f3c63ecb05015e31e46b36f84f2d783c972"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.58.0" ]
revision = "68bd692f5d49b9441b39cb1b13e8f4d777d5c69d"
